import { GoogleTagManager } from "@next/third-parties/google";
import Footer1 from "@/components/footer1/footer1";
import Header from "@/components/header/header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Buzz N Finds",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-KNB7NWC4" />
      <body>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-KNB7NWC4"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <>
          <Header />
          {children}
          <Footer1 />
        </>
      </body>
    </html>
  );
}
